### ISSUE TITLE
Support turtle format on collections

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria#151]
When I go to view a collection on sandbox, e.g. http://sandbox.curationexperts.com/collections/fk4xp77k6z, I get an error if I try to view the turtle format triples - i.e. http://sandbox.curationexperts.com/collections/fk4xp77k6z.ttl, gives me a "something went wrong" page.

In contrast, for individual items, I can view the triples in turtle format:
e.g. http://sandbox.curationexperts.com/lib/ark:/99999/fk4902bz15.ttl

**Comment by jcoyne** [comment]
I don't think this is a bug as much as it is a non-existent feature.
