### ISSUE TITLE
Where is the canonical data for each model?

### ISSUE THREAD

**Issue by bess** [curationexperts/alexandria#16]
Ask Chrissy:

- [ ] In Alexandria, where is the canonical data for each data type?
- [ ] If we were to set up a Hyrax 2 application, would we need to re-ingest all the objects or should we directly migrate some of them?
- [ ] How do they do updates to the data? Is it the same for each data type?

**Comment by val99erie** [comment]
Here is some good info:
https://github.com/ucsblibrary/alexandria/blob/master/doc/ingesting.md#how-etds-are-ingested

**Comment by bess** [comment]
We are de-prioritizing this question because we are taking a full re-ingest off the table for right now.
