### ISSUE TITLE
Investigate GeoWorks

### ISSUE THREAD

**Issue by bess** [curationexperts/alexandria#17]
- [ ] How much work will it be to install GeoWorks into a Hyrax 2 application? 
- [ ] What kind of documentation exists? 
- [ ] What maintenance is required for GeoWorks if we want to adopt it and keep it up to date?

**Comment by val99erie** [comment]
It looks like geo_works currently depends on Hyrax 1.x, not 2.x, so we'd need to update it.
https://github.com/samvera-labs/geo_works/blob/master/geo_works.gemspec#L23

**Comment by val99erie** [comment]
See upgrade notes in the hyrax 2.0.0 release:
https://github.com/samvera/hyrax/releases/tag/v2.0.0

**Comment by val99erie** [comment]
After meetings to discuss new project priorities, it seems unlikely that we'll be using geo_works for the next few months, so I'm closing this story.

**Comment by bess** [comment]
Closing. We are not going to pursue Hyrax 2.
