### ISSUE TITLE
All fields search improvements

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/alexandria#20]
**ACCEPTANCE CRITERIA**
- [x] Work with Chrissy collect a list of the fields that are search
- [x] Determine what fields should be searched
- [x] Collect use cases for what user's are attempting to do but can't

**Comment by val99erie** [comment]
@chrissyrissmeyer  I have a couple questions for you about searching in Alexandria...

At last week's meeting, you had mentioned that Alexandria users weren't able to find the records they expected using the "All Fields" search.

1. Do you have any examples of searches where the user didn't find what they were expecting?

Here are the fields that the "All Fields" search currently hits:

- accession_number
- alternative
- author                  
- keywords
- lc_subject
- location/spatial
- title

2. Which other fields do you want to add to the "All Fields" search?

Thanks!

**Comment by bess** [comment]
Write up here: https://docs.google.com/document/d/1AIqMMwL-P7qFb9OArXCuYxu8PlwDauYwgrpkuPo8JDk/edit#heading=h.lhv2u02w4b1k

Chrissy is going to provide us with a complete metadata mapping and some specific test cases.
