### ISSUE TITLE
Determine requirements for Full text search

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/alexandria#21]
**ACCEPTANCE CRITERIA**

- [x] Interview Chrissy about the needs / use cases for full text search 
- [ ] ~Create storyboards / wireframes for the user experience~
- [x] Develop an estimate with  a few options for implementation

**Comment by val99erie** [comment]
Question:  Just return results of something that matched the search, vs Provide snippets of the search match in context of the document

**Comment by bess** [comment]
Estimate is reflected in the estimate document we're giving to UCSB on 2/22
