### ISSUE TITLE
Set up File serializer

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria#213]
This is an important part of the preservation strategy of Fedora 4. Without it, Fedora is not preserving anything in a human readable way.

This requires installing/configuring fcrepo-message-consumer

**Comment by mark-dce** [comment]
I.E. does UCSD need a human readable version of the metadata to be stored to disk (in addition to the machine accessible RDF).  If so, what formats does FC4 support? Of the available formats, which suits UCSB best?

**Comment by mark-dce** [comment]
We need to do a 1-2 day spike to figure out what the options are so we can give UCSB a specific set of choices based on the available technical options, and or recommend a specific choice.

**Comment by mark-dce** [comment]
All I can find is information about using the FileSerializer to support external (Solr) search applications:
* https://wiki.duraspace.org/display/FEDORA41/FileSerializer
* https://wiki.duraspace.org/display/FEDORA41/External+Search#ExternalSearch-Installandconfigurefcrepo-message-consumer
* https://github.com/fcrepo4/fcrepo-message-consumer

It sounds like we'd have a fair bit of work to do unless the default Solr serialization was acceptable.

**Comment by jcoyne** [comment]
Looks like https://wiki.duraspace.org/display/FEDORA41/RdfPersistenceIndexer is new. That sounds promising.

**Comment by jcoyne** [comment]
This should probably be a conversation with UCSB.  Do they need to have their metadata serialized to ascii to have "preservation" or is having backups of the repository data (as a modeshape binary) sufficient.
