### ISSUE TITLE
Characterize GIS data

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/alexandria#22]
**ACCEPTANCE CRITERIA**
- [x] Record the meeting in BlueJeans
- [x] Determine how much total GIS content UCSB has
- [x] Is all data public? How should we handle access restrictions?
- [x] Determine how many different kinds of  files are there (shapefile vs Tiff, etc)
- [x] Determine what content should be ingested first
- [x] Determine what the most challenging content looks like
- [x] Determine what are the extreme cases (largest files, most attached/supplemental files) 
- [x] Is any of the content nested? Are these modeled as collections, ongoing datasets? etc. 
- [x] Is any of the content ongoing? 
- [x] Determine how we do content updates in general? Do we update the files / replace them, etc? 
- [x] What's the canonical version? Does this live in Alexandria?
- [x] Will you have geo-referenced maps? 
- [x] How should geo-referenced maps display? 
- [x] What is the relationship between a geo-referenced map and its original?
- [x] What is wanted for "harvesting GIS data from CDL"? This was one of the features mentioned by John in our initial meeting, but we don't know what it means.

**Comment by bess** [comment]
Email requesting meeting sent to Tom on 15 Feb

**Comment by bess** [comment]
Interview artifacts here:
* https://docs.google.com/document/d/1dSMxvEnHrsgQJ-MxhJK5ogrEwA3gchkzuW1C0IUnjBg/edit
* https://docs.google.com/document/d/1ztMKKd0_9y4yaP73JVGfxp-oDpWAT_cjdSVEyK0USv4/edit
