### ISSUE TITLE
Determine requirements for CDL harvesting data from Alexandria

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/alexandria#23]
~- [ ]  Interview Tom B. to find out what this entails / means for UCSB~
We interviewed Tom B. and he says CDL doesn't have any GIS data and he doesn't know what this would mean. He said maybe John was talking about research data? We should ask John.
- [ ] Interview Chrissy to determine requirements for CDL harvesting data from Alexandria

**Comment by bess** [comment]
Writeup here: https://docs.google.com/document/d/1AIqMMwL-P7qFb9OArXCuYxu8PlwDauYwgrpkuPo8JDk/edit#heading=h.lhv2u02w4b1k
