### ISSUE TITLE
collection search results view missing metadata

### ISSUE THREAD

**Issue by acozine** [curationexperts/alexandria#239]
If I search for "mountains" from the main page, I see some metadata for each result in my search:
http://sandbox.curationexperts.com/catalog?utf8=%E2%9C%93&search_field=all_fields&q=mountain
if I do the same search within a collection, I see only the title and the thumbnail:
http://sandbox.curationexperts.com/collections/fk4xp77k6z?utf8=%E2%9C%93&cq=mountains&sort=
Same thing if I browse by collection and select a collection - only title and thumbnail.

**Comment by jcoyne** [comment]
Chrissy will send requirements for this.

**Comment by acozine** [comment]
Alex has taken care of this while we were away doing U Mich Press.
