### ISSUE TITLE
Determine requirements for Primo harvest from Alexandria

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/alexandria#24]
- [x] Interview Chrissy to find out what this entails / means for UCSB

**Comment by bess** [comment]
Details here: https://docs.google.com/document/d/1AIqMMwL-P7qFb9OArXCuYxu8PlwDauYwgrpkuPo8JDk/edit#heading=h.lhv2u02w4b1k

Short answer: install OAI-PMH into Alexandria and configure Primo to point at it.
