### ISSUE TITLE
Fix resque deprecation warnings

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria#240]
**ISSUE**
resque and resque-pool both give the following deprecation warning:

> WARNING: This way of doing signal handling is now deprecated. Please see http://hone.heroku.com/resque/2012/08/21/resque-signals.html for more info.

**ACCEPTANCE**
- [ ] resque-pool starts successfully without depreciation warnings

**Comment by mark-dce** [comment]
from @acozine 

The non-deprecated way to signal uses SIGTERM instead of SIGKILL to shut down workers, allowing active jobs to continue for a specified period of time. Specify the environment variable `TERM_CHILD=1` to change the way signals are sent. Default period of time to wait is 4 seconds. Choose a different wait time (in seconds) with `RESQUE_TERM_TIMEOUT=10`. Still need to figure out how/where to set this up for production use with resque-pool. 

See also:
The SIGNALS section of the resque-pool README: https://github.com/nevans/resque-pool
The Update section of this post:  https://quickleft.com/blog/heroku-s-cedar-stack-will-kill-your-resque-workers/ 
And this PR: https://github.com/sshingler/capistrano-resque/pull/99/files 

Also, alternative to resque-pool: https://github.com/spraints/resqued

**Comment by acozine** [comment]
Superceded JIRA ticket no. 512: https://help.library.ucsb.edu/browse/DIGREPO-512
