### ISSUE TITLE
Determine requirements for curator access to master files

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/alexandria#25]
- [x] Interview Chrissy to determine requirements

**Comment by bess** [comment]
Here's a detailed jira ticket describing the issue, and some incomplete code that Alex wrote to address is (which wasn't correct for some reason that Chrissy can explain): https://help.library.ucsb.edu/browse/DIGREPO-692?jql=text%20~%20%22download%22

**Comment by bess** [comment]
Writeup here: https://docs.google.com/document/d/1AIqMMwL-P7qFb9OArXCuYxu8PlwDauYwgrpkuPo8JDk/edit#heading=h.lhv2u02w4b1k
