### ISSUE TITLE
Change the type of a local name

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria#263]
**STORY**
As an administrator, I would like to be able to change the type (personal, group, corporate) of a local name, so that I can fix it if I import or create a bunch of records pointing to a name that got the wrong type assigned when it was created

**DETAILS**
The current solution is to create a new name record with the correct type and then merge the old name (wrong type) into the new name (correct type).  It would be nice, *but low priority* if I could just re-assign the type on the existing local name authority record.

**Comment by val99erie** [comment]
It looks like there is currently no way to cast fedora objects to other models in active-fedora.  See this discussion:
https://groups.google.com/forum/?hl=en#!topic/hydra-tech/jzvhC1AevGw

So, we have a few options:
 * Update active-fedora to allow casting in some situations (if a certain parameter is set, e.g.)
 * As a transaction, delete the old record, and create a new record with the same ID and attributes
 * Find some low-level way to directly edit the data in fedora outside of active-fedora

**Comment by acozine** [comment]
Workaround is to create a new local name with the correct type, then merge the old record into the correct new record. The end result will be a single record with the correct type.
