### ISSUE TITLE
Enable Primo harvest from ADRL

### ISSUE THREAD

**Issue by bess** [curationexperts/alexandria#33]
**ACCEPTANCE CRITERIA**
- [x] Install OAI-PMH endpoint to Alexandria
- [x] Configure according to Alma / Primo instructions
- [x] Ask Chrissy and Ana whether cylinders and ETDs should be part of the OAI Harvest given that they should already exist in the library catalog.
- [ ] ~Make an OAI set for an existing collection that is not cylinders or ETDs (McPeak Collection) for testing~ See explanation below

**Comment by bess** [comment]
Email from Ana re: configuration:
```
The first one to read is https://developers.exlibrisgroup.com/alma/integrations/oai since the integration is with Alma not Primo.  Then Alma publishes the harvested data to Primo.

At the Alma end I have to set up an integration profile as explained in https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/090Integrations_with_External_Systems/030Resource_Management/060Setting_Up_OAI_Integration so I will need all those parameters.

Is this a good starting point?  Do you need more information?

Thanks,
Ana

Ana Fidler
ILS Programmer/Analyst
UCSB Library
(805)893-4787
```

**Comment by mark-dce** [comment]
The Carl Rogers collection has only two items, so it might be a good candidate for initial testing https://www.alexandria.ucsb.edu/collections/f3zc8132.  I.E. it should be easy to tell if _ALL_ the items were harvested properly ;)

**Comment by little9** [comment]
From Chrissy: 

> I asked Catherine about this yesterday and she wants everything (including Cylinders and ETDs). Part of this is that is that allows for flexibility/control is what is exposed to the user via Primo and I think part of it is cataloging-specific (i.e., the cylinder records in the catalog right now are for the physical manifestation of the item and the ADRL records are for the digital manifestation).
