### ISSUE TITLE
Be able to Ingest Sample Data to ADRL

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/alexandria#36]
**ACCEPTANCE CRITERIA**

- [x] Confirm we possess correct collection and record metadata and source files to create full records
 
- [x] Test all formats for import
    - [x] Images - CSV
    - [x] Images - MODS
    -  [x] Cylinders
    -  [x] ETDs
    -  [x] Maps
- [x] Ensure sample data is on sandbox
- [x] Be able to ingest on sandbox server
- [x] Document where to find sample data, and criteria for it (must be sanitized, yet drawn from production site)

**Comment by jenlindner** [comment]
Spoke with Chrissy and Alex yesterday; our sample data contains an outdated field, systemId. (The ark numbers and metadata should be the same.) She says she can get me a few sample MARC records for cylinders (maybe ETDs as well). 

We have a rake task for getting MARC records, via an SRU module, but Alex says that it doesn't work with some of the fields we need from Alma. Ana has filed a ticket with ExLibris to address this.

**Comment by jenlindner** [comment]
Asked Scott on server build call yesterday if we could establish a standard location for sample data (re-instating our old way of handling it), and he agreed, and in fact knows of a directory containing sample data and said he could mount it for us, and check the data with Chrissy as well. I emailed today, asking if we could mount it to /opt/data, which is where I believe we used to have it.

**Comment by jenlindner** [comment]
Also, I got an email response from Chrissy on the current state of the tests, she is going to put in PRs to update where necessary, and also to be able to check fixtures with their metadata validation CI tests. She also agreed to help us get more sample tiffs.

**Comment by jenlindner** [comment]
I broke out a new ticket for making sure the tests are up to date, because that's a different thing.

**Comment by jenlindner** [comment]
We have a small set of sample data, one or two records of each type and their required collection.csv files, in our home directory on the sandbox: `home/adrl/sample_data`.  There's a ticket to create a directory for it, #63. We might want larger quantities, and if so we should create a new ticket for that task when we have the need for them.
