### ISSUE TITLE
Ask permission to add version footers to ADRL

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria#43]
**STORY**
As a project stakeholder, I'd like to be able to understand what version of the application I'm looking at, so that I have better expectations about which features should be live.

**ACCEPTANCE**
- [x] Show Alexandra & Chrissy the solution for Emory
- [x] Determine if there are any reasons that version information shouldn't be displayed publicly based on UCSB policy or practice
- [x] If there's support for the idea, create a wireframe and story; OTHERWISE, document the reasons this doesn't work well for UCSB

**Comment by little9** [comment]
@dunn this is something that we like to do for projects. Here is the documentation for it: 

https://curationexperts.github.io/playbook/every_project/git_sha.html

Right now, the docs assume you are using dotenv for configuration, but that can be changed out. 

Here's what it looks like for Emory (the version bit at the bottom): 

![screenshot-2018-2-26 emory electronic theses and dissertations](https://user-images.githubusercontent.com/4324761/36693097-cd492128-1aff-11e8-81cb-1a8fcdfaa867.png)

Is this something you and Chrissy would want for Alexandria?
