### ISSUE TITLE
Pilot Primo harvest from ADRL

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/alexandria#44]
**ACCEPTANCE CRITERIA**
Given a sandbox or staging ADRL server with a Blacklight OAI-PMH implemented and x number of sample items in the repository: 

- [x] I can read objects from OAI endpoint
- [x] Items show up as expected in the catalogue (potentially, also a staging system)

**Comment by little9** [comment]
Primo was reindexed over the weekend and the URLs are showing up in the metadata. 

They aren't being linked, but that's because of some logic on the Primo side. 

Since there isn't any more I can change on our end I think this is completed.
