### ISSUE TITLE
Add "Larger View" option for images

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria#498]
As an end user, I would like the option to see a larger, more detailed version of images I discover.

**ACCEPTANCE**
- [ ] There is a link on  images that says 'view larger' (or has a magnifying glass, etc.)
- [ ] The link takes me to a view that shows the image at full screen, and lets me zoom in further and pan around if a full resolution view is larger than will fit onscreen

**Comment by acozine** [comment]
Closing in favor of https://help.library.ucsb.edu/browse/DIGREPO-514.
