### ISSUE TITLE
Add "Download" original option for images

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria#499]
As an end user, I would like the option to download the original version of images I discover.

**ACCEPTANCE**
- [ ] There is a link on  images that says 'download original image' (or has a some kind of download icon etc.)
- [ ] Clicking the link downloads a copy of the original  image to my local computer

**Comment by acozine** [comment]
Closing in favor of https://help.library.ucsb.edu/browse/DIGREPO-515.
