### ISSUE TITLE
Restrict "Larger View" and "Download" options to authorized users

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria#500]
As a librarian I want to prevent unauthorized users from accessing restricted images.

**ACCEPTANCE**
-[ ] *Public access:* anyone can see "download" and "view larger" links on public access images
-[ ] *Other access policies:* only the classes of users for whom the policy is true see "download" and "view larger" links

**Comment by acozine** [comment]
Closing in favor of https://help.library.ucsb.edu/browse/DIGREPO-516.
