### ISSUE TITLE
CSV importer type/model error message

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria#501]
If I import a CSV file that doesn't have an appropriate 'type' column, I get the error message: 'ERROR: No model was specified'

ACCEPTANCE:
-[ ] change the error text or the column name so the two are consistent
-[ ] update the README if you to indicate how to set the value in your import file instead of on the command line

**Comment by acozine** [comment]
Closing in favor of https://help.library.ucsb.edu/browse/DIGREPO-517.
