### ISSUE TITLE
Limit creator/contributor by role type

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria#515]
I would like to be able to drill down into creator contributor to show only names with a role like "photographer" or "illustrator" or "author"

**Comment by acozine** [comment]
After discussion 1/29/16 - proposed solution is to put new facets on the page when the user selects a particular contributor. So once I've selected Contributor: Ansel Adams I will see all the objects and new facets for the other roles (e.g Photographer, Editor, etc).

**Comment by acozine** [comment]
Closing in favor of https://help.library.ucsb.edu/browse/DIGREPO-278.
