### ISSUE TITLE
Add 'Cylinder Number' field to Audio Works for Wax Cylinders

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria#552]
Display Label: "Accession Number"
Predicate: http://opaquenamespace.org/ns/cco/accessionNumber --> accession_number
Import Source: parse from 
* MARC field 852
* There may be multiple 852 entries

**EXAMPLES**
<img width="555" alt="adrl2 - 552 - external cylinder holdings" src="https://cloud.githubusercontent.com/assets/3064318/12926492/444a17a2-cf29-11e5-89d0-4efd3d3572db.png">

```
<datafield tag="852" ind1="4" ind2="0">
    <subfield code="a">CU-SB</subfield>
    <subfield code="b">MAIN</subfield>
    <subfield code="c">SPPA</subfield>
    <subfield code="j">Cylinder 12783</subfield>
    <subfield code="n">us</subfield>
    <subfield code="t">2</subfield>
    <subfield code="4">Main Library</subfield>
    <subfield code="5">Special Coll., Performing Arts</subfield>
</datafield>
<datafield tag="852" ind1="4" ind2="0">
    <subfield code="a">CU-SB</subfield>
    <subfield code="b">MAIN</subfield>
    <subfield code="c">SPPA</subfield>
    <subfield code="j">Cylinder 0006</subfield>
    <subfield code="n">us</subfield>
    <subfield code="9">1</subfield>
    <subfield code="4">Main Library</subfield>
    <subfield code="5">Special Coll., Performing Arts</subfield>
</datafield>
```

**Comment by mark-dce** [comment]
In the sample data, MARC record 002556253 will have multiple cylinders associated with the same work.

**Comment by mark-dce** [comment]
@jcoyne I've added the field to import to "Accession Number" and unblocked the ticket. 
Predicate: http://opaquenamespace.org/ns/cco/accessionNumber --> accession_number

**Comment by jcoyne** [comment]
Is the expected output `['Cylinder 12783', 'Cylinder 0006']` or is it `['Cylinder 12783 -- Special Coll., Performing Arts', 'Cylinder 0006 -- Special Coll., Performing Arts']`

**Comment by mark-dce** [comment]
Moving this issue to JIRA https://help.library.ucsb.edu/browse/DIGREPO-519
