### ISSUE TITLE
Display View for Wax Cylinders

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria#555]
**TBD**

As a starting point, make sure we can import and display the metadata displayed here: http://cylinders.library.ucsb.edu/search.php?queryType=@attr+1=1020&num=1&start=1&query=cylinder12783

**Comment by jcoyne** [comment]
There are fields displayed there that we don't have mappings for, for example 028b "Edison Gold Moulded Record". What field is that? What predicate should be used?

**Comment by acozine** [comment]
Will consult with Chrissy and craft a fresh ticket once we know what metadata is required on the wax cylinder pages.
