### ISSUE TITLE
Incorrect behavior of [return] on record-creation interface

### ISSUE THREAD

**Issue by dunn** [curationexperts/alexandria#573]
To reproduce:
1. Login, and go to Admin -> Create a new record
2. Choose Image, hit Next.
3. Type something into the Title field, and hit Return.

Instead of the title being added, I get a "cannot add new empty field" error on the Work Type section:
![screen shot 2016-02-12 at 9 44 09 am](https://cloud.githubusercontent.com/assets/985416/13015374/8becf8cc-d16d-11e5-9ce6-fa212b41da5a.png)

**Comment by acozine** [comment]
Closing in favor of https://help.library.ucsb.edu/browse/DIGREPO-520.
