### ISSUE TITLE
Load ADRL sample data on demo server

### ISSUE THREAD

**Issue by bess** [curationexperts/alexandria#58]
- [x] Ensure sample data is on demo server
- [x] Ensure expected features (e.g., pan/zoom, OAI) work on demo system

**Comment by bess** [comment]
web: ardl-demo.library.ucsb.edu 
ssh: adrl@128.111.87.17

**Comment by jenlindner** [comment]
@bess, is that the correct url for the web site? i think it's adrl-demo.library.ucsb.edu but both are not found.

**Comment by jenlindner** [comment]
https://adrl-demo.library.ucsb.edu gives not found, but http://adrl-demo.library.ucsb.edu does.
