### ISSUE TITLE
Maintain existing ARKs/URLs for images

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/alexandria#583]
Either export full records from the old server such that they can be imported to the new server OR just export a map of accession number and ark and make the images on the new server with that.

**Comment by val99erie** [comment]
@acozine I added a "needs testing" tag to this story.  I think all the development work is done.  When you are doing your dry runs with the UCSB team, please add some comments to this story if you run into any trouble.  If all your testing goes smoothly, go ahead and close the story.

**Comment by acozine** [comment]
We didn't run into any blockers on this one. Re-open if necessary on JIRA.
