### ISSUE TITLE
Import ARKs for Wax Cylinders

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria#607]
attribute | marc source | comments
-------------|------------------|------------------
identifier | field 024, subfield a | where field 024 (ind1="7" with $2="local") - missing in current sample data

Blocked until [DIGREPO-476](https://help.library.ucsb.edu/browse/DIGREPO-476) is complete

**Comment by acozine** [comment]
Closing in favor of https://help.library.ucsb.edu/browse/DIGREPO-521.
