### ISSUE TITLE
Collections show up in search results alongside items

### ISSUE THREAD

**Issue by dunn** [curationexperts/alexandria#650]
I don't know if collections are supposed to show up here or not; if they are then we'll need to fix the rendering.

On http://ucsb.curationexperts.com/catalog?page=95&q=&search_field=all_fields:
![screen shot 2016-03-03 at 5 06 52 pm](https://cloud.githubusercontent.com/assets/985416/13515002/957718dc-e162-11e5-8000-3f5e954d8372.png)

**Comment by chrissyrissmeyer** [comment]
@dunn: My personal feeling is that it is good for collections to show up alongside items in search results (collection is a resource type that you can use to filter). Collections also have subject and genre terms that facilitate discovery.

**Comment by acozine** [comment]
Presuming closed by PR #655.
