### ISSUE TITLE
How to handle MODS typeOfResource field

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria#651]
An email from Chrissy:

> Just an FYI: In an unfortunate turn of events, the MODS type of resource element does not support URIs (which makes sense, I suppose, given that it is a MODS controlled vocabulary): https://www.loc.gov/standards/mods/userguide/typeofresource.html 
So the needed changes to the MODS typeOfResource element for the migration result in invalid MODS records. 

> I am happy to make the changes to the records now so that we can get the collections migrated in a timely fashion, however, long term we really should be using valid records.

> I would suggest mapping from the MODS typeOfResource vocabulary to the appropriate URI instead upon ingest instead. A mapping was already created for DIGREPO-458 (https://help.library.ucsb.edu/browse/DIGREPO-458) — see the last comment for the MODS type of resource mapping.

> DCE: Any thoughts on this? Should I continue making the (invalid) updates to the records for the migration?

**Comment by acozine** [comment]
Closing in favor of https://help.library.ucsb.edu/browse/DIGREPO-522
