### ISSUE TITLE
language URIs are displaying instead of prefLabel

### ISSUE THREAD

**Issue by chrissyrissmeyer** [curationexperts/alexandria#653]
The English language version of the ISO639-2 language prefLabel should display instead of the URI. 

Example:
<http://id.loc.gov/vocabulary/iso639-2/eng> <http://www.w3.org/2004/02/skos/core#prefLabel> "English"@en .

On: http://ucsb.curationexperts.com/catalog?page=95&q=&search_field=all_fields

![957718dc-e162-11e5-8000-3f5e954d8372](https://cloud.githubusercontent.com/assets/4228849/13534266/19d782e8-e1e9-11e5-9051-e3bb694f6271.png)

**Comment by acozine** [comment]
In production, language is not included on the show page. So this ticket is either fixed or moot. Closing.
