### ISSUE TITLE
Ingest to GeoServer by hand

### ISSUE THREAD

**Issue by bess** [curationexperts/alexandria#66]
**GOALS**
* know what our GeoServer derivatives should look like
* verify GeoServer instance is working as expected
* become familiar with GeoServer functionality and end points
* produce a GeoServer end point we can develop against

**ACCEPTANCE CRITERIA**
- [x] Ingest two shape files to GeoServer by hand

**blocked by #64 and #65**

**Comment by bess** [comment]
Use these files:

The first test file, "belvegr" (Belize vegetation), is a polygon shapefile accompanied by a thumbnail created in ArcCatalog (so it's terrible) and the ISO 19139 metadata.  The metadata is complete to the extent that I can do at this point, though I think there will be some ADRL-specific fields with unique identifiers, etc. still to be added, but populated either by the ingest process or by hand later.  (This guess is based on the Stanford workflow.)
https://ucsb.box.com/s/5aft12o70otdmxhdcy91lqs1roelomvt

The second test file, "rbmgrd-t" (DEM) is a geoTIFF accompanied by ISO 19139 metadata and a thumbnail.  Same case as above re metadata.
https://ucsb.box.com/s/hzgx931ozjyx5yg94sf9cwhcg2sh7x9a

**Comment by little9** [comment]
Link to the first file in the sandbox:
http://geoservices-sandbox.library.ucsb.edu:8080/geoserver/ucsb/wms?service=WMS&version=1.1.0&request=GetMap&layers=ucsb:gford-20140000-010015_belvegr&styles=&bbox=261482.890625,1756825.0,384315.90625,2045413.0&width=330&height=768&srs=EPSG:26716&format=application/openlayers

the second:
http://geoservices-sandbox.library.ucsb.edu:8080/geoserver/ucsb/wms?service=WMS&version=1.1.0&request=GetMap&layers=ucsb:RBMGRD&styles=&bbox=27735.426437,1864698.6636660001,271965.426437,1974048.6636660001&width=768&height=343&srs=EPSG:2000&format=application/openlayers
