### ISSUE TITLE
Is LDAP test port number correct?

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria#671]
@acozine is the test LDAP port number of 3389 in the sample config file correct, or should it be port 398 like the development connection:

https://github.com/curationexperts/alexandria/blob/master/config/ldap.yml.template#L17

**Comment by acozine** [comment]
The test port should be 389 to match development. Port 3389 is incorrect. Port 636 is for secure ldap, which is preferable for production. PR coming as soon as Travis has his say.
