### ISSUE TITLE
Set up sandbox environment

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/alexandria#7]
**ACCEPTANCE CRITERIA**
- [ ] ~adrl-sandbox.curationexperts.com~
- [ ] ~Repeatable ansible build~
- [ ] ~On CentOS~
- [ ] Ensure everyone on DCE team can deploy 
- [x] Ensure PR for Capistrano sandbox stage is pushed upstream

**Comment by shanitajohn** [comment]
Scott is setting up the sandbox environment, will connect with DCE when it's in place.

**Comment by mark-dce** [comment]
@bess I'm not able to deploy to the sandbox environment and can't tell for certain if the issue is in my development environment or because my ssh-key is not on the sandbox server.
