### ISSUE TITLE
Write a minimal Darlingtonia Mapper for ISO GeoMetadata

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria#73]
Requires #68 to be completed first

- [x] Must populate all required fields for GeoBlacklight
- [x] Write an additional ticket for any additional fields desired by UCSB
- [x] If any of the required fields is missing from the CSV file, when I run the importer, I will get an error message that explains which required columns are missing.

**Comment by val99erie** [comment]
The required fields are listed here:
https://github.com/samvera-labs/geo_works/blob/master/config/discovery/geoblacklight-schema.json#L11-L17

Note that the solr_geom field has 4 components, so I'm not sure if that should be 1 or 4 columns in the CSV file.

**Comment by val99erie** [comment]
@chrissyrissmeyer  For the coverage / bounding box field,  does UCSB have a strong preference about whether the input CSV file should have 4 separate columns for S W N E values, or should all 4 values be in a single column?

**Comment by val99erie** [comment]
Note:  `dc_identifier` is a required field for geoblacklight's solr schema, but it shouldn't be in the CSV file.  It appears that geoblacklight uses that field (instead of `id`) to store the fedora ID of the record.

**Comment by val99erie** [comment]
I got a reply from Chrissy on slack:  

> bounding box is 4 columns in the CSV

**Comment by jenlindner** [comment]
#47 is for additional metadata UCSB would like ingested by Iris and displayed by Aster
