### ISSUE TITLE
Ensure Geo derivatives are transferred to GeoServer

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria#76]
From the rails console
- [ ] Ensure derivatives are generated
- [ ] Ensure derivatives are available from GeoServer
- [ ] Ensure GeoTiffs create the expected derivatives 
- [ ] Ensure Shapefiles the expected derivatives
- [ ] Ensure derivatives are available at the expected GeoServer endpoint

DETAILS:
See outcomes from #66 for further detail of "the expected..."

**Comment by val99erie** [comment]
Related to this story:  https://github.com/curationexperts/iris/issues/18

**Comment by shanitajohn** [comment]
Superseded by #77
