### ISSUE TITLE
Ensure Geo Importer sends derivatives to GeoServer

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/alexandria#77]
**ACCEPTANCE CRITERIA**
After I ingest a new object with the importer:
- [x] I can access its derivative at the expected endpoint in GeoServer
- [x] Ensure derivatives are generated
- [x] Ensure derivatives are available from GeoServer
- [x] Ensure GeoTiffs create the expected derivatives 
- [x] Ensure Shapefiles the expected derivatives
- [x] Ensure derivatives are available at the expected GeoServer endpoint

Note: Bug encountered and documented in https://github.com/curationexperts/iris/issues/50

**Comment by val99erie** [comment]
Related to story https://github.com/curationexperts/iris/issues/18

**Comment by bess** [comment]
Sorry, I shouldn't have closed this without talking to Val first.
