### ISSUE TITLE
Set up demo environment (UCSB)

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/alexandria#8]
- [x] Scott is setting this up for DCE
- [x] Add cap deploy target

**Comment by bess** [comment]
On March 5, Scott said he'd have this to us by March 7.

**Comment by bess** [comment]
Environment provided on March 7. We can deploy to these systems but they do not have port 80 open outside UCSB. Waiting on that to be fixed and then I'll close this ticket.

**Comment by bess** [comment]
And we're up: http://adrl-demo.library.ucsb.edu/
