### ISSUE TITLE
Document infrastructure architecture

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/alexandria#9]
**ACCEPTANCE CRITERIA**
Interview questions
- [x] What's load balanced?
- [x] Are you expecting that our services (e.g., GeoServer, Cantaloupe) will be load balanced?
- [x] What's the best way to get new services into production?
- [x] Do they have a GeoServer instance already? How can we get access to that?
- [x] Agree on Ansible practices

**Comment by bess** [comment]
Email sent 2/15 requesting a phone call

**Comment by bess** [comment]
Notes here: https://docs.google.com/document/d/1w5VmwoMHhQ_4qBqX4yS8K867p0WizO-NWzAb28rFPPo/edit
