### ISSUE TITLE
Configure Iris with Aster and Geoserver connection details (sandbox)

### ISSUE THREAD

**Issue by little9** [curationexperts/alexandria#92]
**ACCEPTANCE CRITERIA**

- [x] If I run the importer on Iris-sandbox, I should see the records show up on Aster-sandbox. 
- [x] If I run the importer on Iris-sandbox, I should see the records show up in GeoServer

**These are set with environment variables:**

https://github.com/samvera-labs/geo_works/blob/master/config/geoblacklight.yml

https://github.com/samvera-labs/geo_works/blob/master/config/geoserver.yml

**Comment by val99erie** [comment]
I could be wrong, but I think the `PUBLIC_GEOSERVER_DERIVATIVES_PATH`:

- needs to be a directory under the tomcat home
- the Hyrax derivatives dir needs to be mounted or symlinked into that directory

So, for example, in my dev env:

- `export PUBLIC_GEOSERVER_DERIVATIVES_PATH="/usr/local/Cellar/tomcat/9.0.6/libexec/webapps/geoserver/data/derivatives"`
- That derivatives dir is a symlink back to my Iris workspace `tmp/derivatives`
